DROP DATABASE IF EXISTS FunctionDB;
CREATE DATABASE FunctionDB;
USE FunctionDB;
DELIMITER $$
CREATE FUNCTION Square(num INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN num*num;
END $$
DELIMITER ;

SELECT Square(5) AS Result;
SELECT Square(10) AS Resul;
