DROP DATABASE IF EXISTS TriggerDB;
CREATE DATABASE TriggerDB;
USE TriggerDB;
CREATE TABLE Employee(
EmpID INT PRIMARY KEY,
EmpName VARCHAR(30),
Salary INT
);
DELIMITER $$
CREATE TRIGGER CheckSalary
BEFORE INSERT
ON Employee
FOR EACH ROW
BEGIN
IF NEW.Salary<10000 THEN
SET NEW.Salary=10000;
END IF;
END $$
DELIMITER ;
INSERT INTO Employee VALUES
(101,'Rahul',8000),
(102,'Anitha',25000),
(103,'Kiran',9000);
SELECT * FROM Employee;
